### ISSUE TITLE
Lightcurve visualisation/analysis

### ISSUE THREAD

**Issue by TomWagg** [tobin-wainer/elk#41]
- [x] Move all lightcurve plotting into the plot module (per #20)
- [x] Add functions in lightcurve class to access this plotting easily
- [x] Create a function that adds all lightcurve analysis to a multiple subplot plot (it'll be cute)

**Comment by TomWagg** [comment]
For the panels I'm thinking:

1. Lightcurve itself
2. Autocorrelation funtion
3. Periodogram
4. A blank one with annotations of the various stats like Stetson, von Neumann etc

**Comment by tobin-wainer** [comment]
Incorporate the GIF!
