### ISSUE TITLE
Making Spline Knots a tunable knob

### ISSUE THREAD

**Issue by tobin-wainer** [tobin-wainer/elk#54]
Right now we set it to 4, but this number should be allowed to be changed. 

If None:
Then return the LC without this corrector.

**Comment by TomWagg** [comment]
Two clarifications:

1. Do you want the default to be 4 or 5 knots? (It is currently 5 in the code)
2. What does the LC without the corrector mean? Do we take `spline_dm1` out of the `DesignMatrixCollection` or is this something else?

**Comment by TomWagg** [comment]
Bump on question 2 @tobin-wainer

**Comment by tobin-wainer** [comment]
@TomWagg Yes, don't have spline_dm in the DisignMatrixCollection. Right now, this is called "systematics_model " where the DisignMatrixCollection is only the CBV's and the PCA.
