### ISSUE TITLE
Try giving a list of potential stars that are leading to a given frequency spike

### ISSUE THREAD

**Issue by TomWagg** [tobin-wainer/elk#62]
Use the individual pixel periodograms to find likely locations and then use `astroquery` to search SIMBAD and find some likely candidates

**Comment by tobin-wainer** [comment]
Need to flip the way the pixels are read into the wcs... 

 if the argwhere returns [48, 62] what we need to put into the pixel_to_world is (62, 48)

If I do "tess_wcs.pixel_to_world(*np.fliplr(solutions[0])).icrs" I get the correct thing, but if there are multiple solutions and I do:
tess_wcs.pixel_to_world(*np.fliplr(solutions)).icrs
then its wrong again....

**Comment by TomWagg** [comment]
Ah gotcha so the (x, y) is just backwards? Perhaps we just need `*query_pixels.T[::-1]` in that case (which will reverse the x-y axes)

**Comment by tobin-wainer** [comment]
I tried that as well... but that reverses the entire array, not the individual pairs
