### ISSUE TITLE
CBVs warning causing very long correction

### ISSUE THREAD

**Issue by tobin-wainer** [tobin-wainer/elk#65]
For certain sectors, getting a warning saying: "Extrapolation of CBVs appears to be necessary. Extrapolated values will be filled with zeros. Recommend setting extrapolate=True
Some interpolated (or extrapolated) CBV values have been set to zero"

Sectors which have this error are taking ~4 hours.

**Comment by TomWagg** [comment]
Intriguing - do you have any idea what situations you would need to extrapolate a CBV in? This is after fixing the aperture mask right?

**Comment by tobin-wainer** [comment]
After fixing the aperture mask. But I have literally no idea when this would be needed. It wasn't in the older version of lk I was using.
