### ISSUE TITLE
Periodogram Wishlist

### ISSUE THREAD

**Issue by tobin-wainer** [tobin-wainer/elk#66]
Would like the frequencies of the LSP peaks to returned as well as the power and frequencies. 

Just like I can do lcs[0].periodogram or lcs[0].periodogram_freqs, would love to do lcs[0].periodogram_peaks

Also include the FAP and a yellow horizontal line for the FAP (see Tobin for code)

**Comment by TomWagg** [comment]
So you want the peak frequencies stored directly in the class rather than in the stats dictionary? (They are stored in `lc.stats["peak_freqs"]` atm)

**Comment by tobin-wainer** [comment]
Yeah. It would be nice if it was part of the class like the periodogram and periodogram_freqs, just for simplicity in using. SO the options could then be, periodogram, periodogram_freqs, and periodogram_peaks
