### ISSUE TITLE
Incorporate Phase folded Lightcurves

### ISSUE THREAD

**Issue by tobin-wainer** [tobin-wainer/elk#68]
Super easy to do, but might help with diagnostics.

code is:
phased=(c.lcs[i].corrected_lc.time.value-c.lcs[i].corrected_lc.time.value[0])%{whatever_period_you_want}

Then plot (i.e):
plt.scatter(phased, c.lcs[i].corrected_lc.flux.value, color='k', s=1)

Might be really nice as a feature like .plot_periodogram. Like lcs.plot_folded_lc({period})

**Comment by TomWagg** [comment]
How about we make it a flag in the `.plot` function? i.e. `lc.plot(fold=True)`

**Comment by tobin-wainer** [comment]
Only thing is a period needs to be specified and needs to be tunable. So lc.plot(fold=True, period=XXX)
