### ISSUE TITLE
Provide an option to ignore the scattered light test. 

### ISSUE THREAD

**Issue by tobin-wainer** [tobin-wainer/elk#71]
I think this might be nice for people who just want to know what a LC looks like, and don't particularly care if there is scattered light. 

Because you sped it up so much, we should still calculate it, but if "Ignore_Scattered_Light_Test" = True, then maybe just return a Warning saying that it doesn't pass the test, but still gives the light curve. 

This shouldn't be the default, but maybe a nice option.

**Comment by TomWagg** [comment]
Nice, we can repurpose the `debug` flag to do this (it almost does this already :D)

**Comment by tobin-wainer** [comment]
Perfect!!
